### ISSUE TITLE
Redis server connection refusal

### ISSUE THREAD

**Issue by mdabir1203** [shamantechnology/RedAGPT#16]
Issue Description:
Redis server connection refused  and virtualenv cannot find redis-cli

------------------------------
<img width="915" alt="image" src="https://github.com/shamantechnology/RedAGPT/assets/66947064/1c510f6a-8082-4e84-973f-7931e2206a0c">
----   --- ------------------  
<img width="643" alt="image" src="https://github.com/shamantechnology/RedAGPT/assets/66947064/940c8943-2c92-40cc-b7ac-241de46ff4c9">

Steps to Reproduce:
1. Running python main.py
2. After you put an url

Platform : Github Codepsaces (Linux)

**Comment by risingsunomi** [comment]
You will need to be running the redis docker redis-stack-server

`sudo docker run -d --name redis-stack -p 6379:6379 redis/redis-stack-server:latest`

If you want to run it locally on another computer, you can run it this way but will still need to handle the firewall rules

`sudo docker run -d --name redis-stack -p 0.0.0.0:6379:6379 redis/redis-stack-server:latest`

If running on WSL via windows you will need to open the port 6379 in and out along with running the network shell command in powershell

`netsh interface portproxy add v4tov4 listenport=6379 listenaddress=0.0.0.0 connectport=6379 connectaddress=<linux IP from ifconfig>`
